"""生成 src/sprite_anchors.h：每一帧的头部相似变换（从第 20 帧「中性站立」坐标映射到该帧），供围巾跟随动作。

做法：在第 20 帧的脸部取一组采样点，用 assets/motion-vectors.bin 中 (i,20) 的光流把它们映射到第 i 帧，
再用加权最小二乘拟合「缩放 + 旋转 + 平移」。光流不可靠的几帧（睡觉、打滚、嗅闻）用手工标注的两点对应。
只读取素材与向量，不修改任何图像。依赖：numpy。
"""
from pathlib import Path
import json, struct
import numpy as np

root = Path(__file__).resolve().parent.parent
data = (root / 'assets/motion-vectors.bin').read_bytes()
count, grid = struct.unpack('<II', data[8:16]); entry = 4 + grid * grid * 4 * 2
flows = {}
for i in range(count):
    a, b = struct.unpack('<HH', data[16 + i * entry:20 + i * entry])
    flows[(a, b)] = np.frombuffer(data[20 + i * entry:16 + (i + 1) * entry], dtype='<i2').reshape(grid, grid, 4) / 64.

def sample(v, x, y):
    gx, gy = x * (grid - 1) / 255., y * (grid - 1) / 255.
    ix, iy = min(grid - 2, int(gx)), min(grid - 2, int(gy)); fx, fy = gx - ix, gy - iy
    return v[iy, ix] * (1 - fx) * (1 - fy) + v[iy, ix + 1] * fx * (1 - fy) + v[iy + 1, ix] * (1 - fx) * fy + v[iy + 1, ix + 1] * fx * fy

def map20(i, p):
    if i == 20: return p
    x, y = p
    if (i, 20) in flows: v = sample(flows[(i, 20)], x, y); return (x + v[2], y + v[3])
    v = sample(flows[(20, i)], x, y); return (x + v[0], y + v[1])

src = np.array([(x, y) for x in range(112, 200, 6) for y in range(96, 150, 6)], float)
def fit(i):
    dst = np.array([map20(i, tuple(p)) for p in src]); w = np.ones(len(src))
    for _ in range(8):   # 迭代重加权，压低被爪子遮挡处的光流误差
        ms, md = (w[:, None] * src).sum(0) / w.sum(), (w[:, None] * dst).sum(0) / w.sum()
        a, b = src - ms, dst - md
        den = (w * (a ** 2).sum(1)).sum()
        c = (w * (a[:, 0] * b[:, 0] + a[:, 1] * b[:, 1])).sum() / den
        s = (w * (a[:, 0] * b[:, 1] - a[:, 1] * b[:, 0])).sum() / den
        M = np.array([[c, -s], [s, c]]); r = np.linalg.norm(a @ M.T + md - dst, axis=1)
        w = 1 / (1 + (r / max(1.0, np.median(r) * 1.5)) ** 2)
    return M, md - ms @ M.T

def two_point(p1, p2, q1, q2):
    p1, p2, q1, q2 = map(np.array, (p1, p2, q1, q2)); vp, vq = p2 - p1, q2 - q1
    k = np.hypot(*vq) / np.hypot(*vp); ang = np.arctan2(vq[1], vq[0]) - np.arctan2(vp[1], vp[0])
    M = np.array([[k * np.cos(ang), -k * np.sin(ang)], [k * np.sin(ang), k * np.cos(ang)]]); return M, q1 - M @ p1

L20, R20 = (110, 160), (194, 162)   # 第 20 帧围巾左右端
manual = {4: two_point(L20, R20, (103, 180), (184, 201)), 9: two_point((149, 133), (189, 130), (107, 140), (138, 115)),
          10: two_point(L20, R20, (96, 214), (170, 236)), 55: two_point(L20, R20, (98, 172), (182, 150)),
          56: two_point(L20, R20, (100, 172), (183, 135))}
nudge = {38: 3, 39: 7, 40: 8}   # 打哈欠时嘴张得大，围巾往下挪一点
rows = []
for i in range(60):
    M, t = manual[i] if i in manual else fit(i)
    rows.append((M[0, 0], M[1, 0], t[0], t[1] + nudge.get(i, 0), 0.0 if i == 10 else 1.0))   # 嗅闻时脖子被头挡住
lines = ['#pragma once', '// Generated by tools/build_scarf_anchors.py: per-frame head similarity transform (frame 20 space -> frame space).',
         "// x' = a*x - b*y + tx, y' = b*x + a*y + ty. visible=0 means the neck is hidden in that pose.",
         'struct HeadAnchor { float a,b,tx,ty,visible; };', 'constexpr HeadAnchor HEAD_ANCHORS[60] = {']
lines += ['    {%.5ff,%.5ff,%.3ff,%.3ff,%.1ff},' % r for r in rows] + ['};']
(root / 'src/sprite_anchors.h').write_text('\n'.join(lines) + '\n', encoding='utf8')
(root / 'assets/head-anchors.json').write_text(json.dumps([dict(zip(['a', 'b', 'tx', 'ty', 'visible'], map(float, r))) for r in rows], indent=1), encoding='utf8')
print('Wrote head anchors for 60 frames.')
