"""Read sprite bounds and emit registration metadata; never modifies the source artwork."""
from pathlib import Path
import json
import numpy as np
from PIL import Image
from scipy import ndimage

root = Path(__file__).resolve().parent
names = ['hedgehog-atlas.png','hedgehog-extra.png','motion-walk.png','motion-relax.png','motion-play.png']
frames = []
for sheet, name in enumerate(names):
    im = Image.open(root/'assets'/name)
    alpha = np.array(im.getchannel('A'))
    boxes = []
    if sheet < 2:
        for i in range(6):
            ox,oy = i%3*512,i//3*512
            yy,xx = np.where(alpha[oy:oy+512,ox:ox+512]>20)
            boxes.append((ox+int(xx.min()),oy+int(yy.min()),ox+int(xx.max())+1,oy+int(yy.max())+1))
    else:
        labels,_ = ndimage.label(alpha>20)
        counts = np.bincount(labels.ravel())
        ids = [i for i in np.where(counts>10000)[0] if i]
        assert len(ids)==16, (name,'expected sixteen separate sprites',len(ids))
        for i in ids:
            yy,xx=np.where(labels==i)
            boxes.append((int(xx.min()),int(yy.min()),int(xx.max())+1,int(yy.max())+1))
        boxes.sort(key=lambda b:(b[1]+b[3])/2)
        boxes = sum([sorted(boxes[r:r+4],key=lambda b:(b[0]+b[2])/2) for r in range(0,16,4)],[])
    neutral_height = (boxes[8][3]-boxes[8][1]) if sheet==2 else np.median([boxes[i][3]-boxes[i][1] for i in (0,7,8,15)]) if sheet>2 else 474
    for i,(l,t,r,b) in enumerate(boxes):
        # Registration removes camera-size drift in the walk/blink loop. Bending poses retain their actual height.
        ratio = 190./((b-t) if sheet==2 and i<12 else neutral_height)
        pad=2
        rect=[max(0,l-pad),max(0,t-pad),min(im.width,r+pad),min(im.height,b+pad)]
        assert rect[0]<l and rect[1]<t and rect[2]>r and rect[3]>b, (name,i,'source clipped')
        frames.append(dict(sheet=sheet,asset=name,rect=rect,pivot_x=(l+r)/2-rect[0],pivot_y=b-rect[1],ratio=round(ratio,8)))
assert len(frames)==60
(root/'assets'/'sprite-metadata.json').write_text(json.dumps(frames,indent=2),encoding='utf8')
lines=['#pragma once','// Generated by build_sprite_metadata.py; registered foot pivots and per-clip scale.',
       'struct SpriteSpec { int sheet,x,y,w,h; float pivotX,pivotY,ratio; };',
       'constexpr SpriteSpec SPRITES[60] = {']
for f in frames:
    l,t,r,b=f['rect']
    lines.append('    {%d,%d,%d,%d,%d,%.6ff,%.6ff,%.8ff},' % (f['sheet'],l,t,r-l,b-t,f['pivot_x'],f['pivot_y'],f['ratio']))
lines+=['};']
(root/'sprite_metadata.h').write_text('\n'.join(lines)+'\n',encoding='utf8')
print('Registered 60 sprites with stable foot pivots; source PNGs unchanged.')
